### ISSUE TITLE
Vim lightline seems missing onehalflight option

### ISSUE THREAD

**Issue by rudenkornk** [sonph/onehalf#125] opened 2021-12-13 11:26 UTC
Directory vim/autoload/lightline/colorscheme has onehalfdark.vim but does not have onehalflight.vim
I have no errors with
let g:lightline = { 'colorscheme': 'onehalfdark' }

But I get an error "lightline.vim: Could not load colorscheme onehalflight" if using light option

**Comment by dwettstein** [comment] 2022-01-24 07:47
Duplicate of #100

**Closed** 2022-01-24 16:49 UTC
